[package]
name = "loadavg"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[target.'cfg(target_os = "linux")'.dependencies]
glob = "0.3.0"

[dependencies]
anyhow = "1.0.70"
cfg-if = "1.0.0"
libc = "0.2.141"
