version: 2
jobs:
  clang:
    docker:
      - image: penryu/cdev:latest
    environment:
      - CC: clang
    steps:
      - checkout
      - run:
          name: make
          command: |
                    make
                    ./loadavg
      - run:
          name: cmake
          command: |
                    mkdir build
                    cd build
                    cmake .. -G Ninja
                    ninja
                    ./loadavg
  gcc:
    docker:
      - image: penryu/cdev:latest
    environment:
      - CC: gcc
    steps:
      - checkout
      - run:
          name: make
          command: |
                    make
                    ./loadavg
      - run:
          name: cmake
          command: |
                    mkdir build
                    cd build
                    cmake .. -G Ninja
                    ninja
                    ./loadavg
