version: 2
jobs:

#  alpine-clang:
#    docker:
#      - image: penryu/cbuilder:alpine
#    environment:
#      - CC: clang
#    steps:
#      - checkout
#      - run: cc --version
#      - run: make
#      - run: ./loadavg
#
#  alpine-gcc:
#    docker:
#      - image: penryu/cbuilder:alpine
#    environment:
#      - CC: gcc
#    steps:
#      - checkout
#      - run: cc --version
#      - run: make
#      - run: ./loadavg
#
#  centos-clang:
#    docker:
#      - image: penryu/cbuilder:centos
#    environment:
#      - CC: clang
#    steps:
#      - checkout
#      - run: cc --version
#      - run: make
#      - run: ./loadavg
#
#  centos-gcc:
#    docker:
#      - image: penryu/cbuilder:centos
#    environment:
#      - CC: gcc
#    steps:
#      - checkout
#      - run: cc --version
#      - run: make
#      - run: ./loadavg
#
#  debian-clang:
#    docker:
#      - image: penryu/cbuilder:debian
#    environment:
#      - CC: clang
#    steps:
#      - checkout
#      - run: cc --version
#      - run: make
#      - run: ./loadavg

  debian-gcc:
    docker:
      - image: penryu/cbuilder:debian
#    environment:
#      - CC: gcc
    steps:
      - checkout
      - run: cc --version
      - run: make
      - run: ./loadavg

workflows:
  version: 2
  temp:
    jobs:
      - debian-gcc
#  alpine:
#    jobs:
#      - alpine-clang
#      - alpine-gcc
#  centos:
#    jobs:
#      - centos-clang
#      - centos-gcc
#  debian:
#    jobs:
#      - debian-clang
#      - debian-gcc
